name: ones_blog
description: OnesBlog Applications
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.4

dependencies:
  bloc: ^8.0.3
  carousel_slider: ^4.1.1
  device_info_plus: ^5.0.5
  dropdown_button2: ^1.8.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  http: ^0.13.5
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  stream_transform: ^2.0.1

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/background/
    - images/element/
    - images/icon/
    - images/text/
